name: poc-yaml-swagger-ui-resources
rules:
    r0:
        request:
            method: GET
            path:  /swagger-resources
        expression: response.status == 200 && responseBody.contains("swagger")
    r1:
        request:
            method: GET
            path: /api/swagger-resources
        expression: response.status == 200 && responseBody.contains("swagger")
    r2:
        request:
            method: GET
            path: /v1/swagger-resources
        expression: response.status == 200 && responseBody.contains("swagger")
expression: r0() || r1() || r2()