name: poc-yaml-swagger-ui-json
rules:
    r0:
        request:
            method: GET
            path: /swagger.json
        expression: response.status == 200 && responseBody.contains("swagger")
    r1:
        request:
            method: GET
            path: /v1/swagger.json
        expression: response.status == 200 && responseBody.contains("swagger")
    r2:
        request:
            method: GET
            path: /v2/swagger.json
        expression: response.status == 200 && responseBody.contains("swagger")
expression: r0() || r1() || r2()